// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3PC25ijtQZhI29nnYuzx3PFVx6OtqPdM',
    appId: '1:282569767384:web:a386f6931b5d375f741aad',
    messagingSenderId: '282569767384',
    projectId: 'potential-potato',
    authDomain: 'potential-potato.firebaseapp.com',
    storageBucket: 'potential-potato.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNiUW8DEu6Pm0mBqJ1dCn0zs03W11croE',
    appId: '1:282569767384:android:48a01ba31e0ae4a9741aad',
    messagingSenderId: '282569767384',
    projectId: 'potential-potato',
    storageBucket: 'potential-potato.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOXK1Z7YPIEc802gv3GMoAT2YltOAGSwk',
    appId: '1:282569767384:ios:4ac5e47fe0da495e741aad',
    messagingSenderId: '282569767384',
    projectId: 'potential-potato',
    storageBucket: 'potential-potato.appspot.com',
    iosBundleId: 'com.example.potentialPotato',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOXK1Z7YPIEc802gv3GMoAT2YltOAGSwk',
    appId: '1:282569767384:ios:449459375df64dc2741aad',
    messagingSenderId: '282569767384',
    projectId: 'potential-potato',
    storageBucket: 'potential-potato.appspot.com',
    iosBundleId: 'com.example.potentialPotato.RunnerTests',
  );
}
